### ISSUE TITLE
[1.16.5]  Mega gaia crates can crash just because you renamed them

### ISSUE THREAD

**Issue by Maks1234Ty** [Andromander/Gaia-Dimension#107] opened 2021-05-08 09:30 UTC
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.16.5
 - Forge: 1.16.5-forge-36.1.4
 - Gaia Dimension: gaiadimension-1.16.5-1.3.3-unofficial-3.jar

**To Reproduce:**
1. Rename Mega crate to anything example "Oak Wood"
2. Place it down
3. Break it
4. repeat step 2 and 3 to crash and potentialy revent chunk to original state

**Describe the bug**
When you break a Mega crate with changed name (example "Oak wood") then another layer of [ ] will be added
resulting in name being longer and longer [[[[[[Oak Wood]]]]]]

**Screenshots**
https://streamable.com/57b70x

**Comment by Andromander** [comment] 2021-05-08 10:46
Duplicate of #105

**Closed as completed by Andromander** 2021-05-08 10:46 UTC
Labels: bug, duplicate
